--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/07/2019 00:41:51
-- Server version: 5.5.5-10.3.15-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS compra_venta;

CREATE DATABASE compra_venta
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Set default database
--
USE compra_venta;

--
-- Create table `persona`
--
CREATE TABLE persona (
  ID int(11) NOT NULL AUTO_INCREMENT,
  ID_PERSONERIA tinyint(4) NOT NULL,
  DIRECCION varchar(300) DEFAULT NULL,
  TELEFONO varchar(20) DEFAULT NULL,
  CELULAR varchar(20) DEFAULT NULL,
  EMAIL varchar(200) DEFAULT NULL,
  PAGINA_WEB varchar(200) DEFAULT NULL,
  ES_VIGENTE bit(1) NOT NULL DEFAULT b'1',
  FECHA_CREACION datetime NOT NULL DEFAULT CURRENT_TIMESTAMP (),
  USUARIO_CREACION varchar(20) NOT NULL,
  FECHA_MODIFICACION datetime DEFAULT NULL,
  USUARIO_MODIFICACION varchar(20) DEFAULT NULL,
  ES_BORRADO bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
COMMENT = 'Almacena información general de personas';

--
-- Create table `usuario`
--
CREATE TABLE usuario (
  ID_PERSONA int(11) NOT NULL,
  USUARIO varchar(20) NOT NULL,
  CONTRASENIA varchar(20) NOT NULL,
  ES_VIGENTE bit(1) NOT NULL DEFAULT b'1',
  FECHA_CREACION datetime NOT NULL DEFAULT CURRENT_TIMESTAMP (),
  USUARIO_CREACION varchar(20) NOT NULL,
  FECHA_MODIFICACION datetime DEFAULT NULL,
  USUARIO_MODIFICACION varchar(20) DEFAULT NULL,
  ES_BORRADO bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (ID_PERSONA)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
COMMENT = 'Almacena información de los usuarios que acceden al sistema.';

--
-- Create foreign key
--
ALTER TABLE usuario
ADD CONSTRAINT FK_usuario_ID_PERSONA FOREIGN KEY (ID_PERSONA)
REFERENCES persona (ID) ON DELETE NO ACTION;

--
-- Create table `persona_natural`
--
CREATE TABLE persona_natural (
  ID_PERSONA int(11) NOT NULL,
  PRIMER_APELLIDO varchar(100) NOT NULL,
  SEGUNDO_APELLIDO varchar(100) DEFAULT NULL,
  NOMBRES varchar(100) NOT NULL,
  ID_SEXO tinyint(4) NOT NULL,
  FECHA_NACIMIENTO date DEFAULT NULL,
  ES_VIGENTE bit(1) NOT NULL DEFAULT b'1',
  FECHA_CREACION datetime NOT NULL,
  USUARIO_CREACION varchar(20) NOT NULL,
  FECHA_MODIFICACION datetime DEFAULT NULL,
  USUARIO_MODIFICACION varchar(20) DEFAULT NULL,
  ES_BORRADO bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (ID_PERSONA)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
COMMENT = 'Almacena información de las personas naturales';

--
-- Create foreign key
--
ALTER TABLE persona_natural
ADD CONSTRAINT FK_persona_natural_ID_PERSONA FOREIGN KEY (ID_PERSONA)
REFERENCES persona (ID) ON DELETE NO ACTION;

--
-- Create table `persona_juridica`
--
CREATE TABLE persona_juridica (
  ID_PERSONA int(11) NOT NULL,
  RAZON_SOCIAL varchar(500) NOT NULL,
  ES_VIGENTE bit(1) NOT NULL DEFAULT b'1',
  FECHA_CREACION datetime NOT NULL DEFAULT CURRENT_TIMESTAMP (),
  USUARIO_CREACION varchar(20) NOT NULL,
  FECHA_MODIFICACION datetime DEFAULT NULL,
  USUARIO_MODIFICACION varchar(20) DEFAULT NULL,
  ES_BORRADO bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (ID_PERSONA)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
COMMENT = 'Almacena información de las personas jurídicas.';

--
-- Create foreign key
--
ALTER TABLE persona_juridica
ADD CONSTRAINT FK_persona_juridica_ID_PERSONA FOREIGN KEY (ID_PERSONA)
REFERENCES persona (ID) ON DELETE NO ACTION;

-- 
-- Dumping data for table persona
--
-- Table compra_venta.persona does not contain any data (it is empty)

-- 
-- Dumping data for table usuario
--
-- Table compra_venta.usuario does not contain any data (it is empty)

-- 
-- Dumping data for table persona_natural
--
-- Table compra_venta.persona_natural does not contain any data (it is empty)

-- 
-- Dumping data for table persona_juridica
--
-- Table compra_venta.persona_juridica does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;